# Generated by Django 6.0.4 on 2026-08-25 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='unit_schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.unitschedule'),
        ),
        migrations.AlterField(
            model_name='unitschedule',
            name='date',
            field=models.DateField(blank=True, help_text='Specific date / null for recurring templates', null=True),
        ),
        migrations.AlterField(
            model_name='unitschedule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this schedule is currently active'),
        ),
    ]
