# Generated by Django 6.0.4 on 2026-08-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_unit_schedule_alter_unitschedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='unit_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.unitschedule'),
        ),
    ]
