# Generated by Django 6.0.4 on 2026-08-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_unit_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitschedule',
            name='recurrence',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=10),
        ),
    ]
