# Generated by Django 6.0.4 on 2026-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_unitreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitschedule',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
