# Generated by Django 6.0.4 on 2026-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('street', 'house_number', 'building_name'), name='unique_address_per_street'),
        ),
    ]
