# Generated by Django 6.0.4 on 2026-08-22 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_unique_address_per_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='image',
        ),
    ]
