# Generated by Django 6.0.4 on 2026-08-28 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_remove_unit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(help_text='ISO 3166-1 alpha-3 code (USA, RUS, etc.)', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='ISO code must contain exactly three uppercase Latin letters.', regex='^[A-Z]{3}$')]),
        ),
    ]
