# Generated by Django 6.0.4 on 2026-08-28 21:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_country_iso_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(help_text='ISO 3166-1 alpha-3 code (USA, RUS, etc)', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='ISO code must contain exactly three uppercase letters', regex='^[A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(help_text="Region code in 'AAA-XX' form, where AAA is the countryISO code and XX is a region letter or digit code", max_length=20, validators=[django.core.validators.RegexValidator(message='Use letters, digits, and hyphens only', regex='^[A-Za-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='street',
            name='street_code',
            field=models.CharField(blank=True, help_text='official or external street identifier', max_length=50, unique=True),
        ),
    ]
