# Generated by Django 6.0.4 on 2026-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_country_iso_code_alter_region_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='street_code',
            field=models.CharField(blank=True, help_text='official or external street identifier', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='street',
            constraint=models.UniqueConstraint(fields=('street_code', 'district'), name='unique_street_code_per_district'),
        ),
    ]
